
services:
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: tunnel
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    command: tunnel run
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/config/cloudflared.yml:/etc/cloudflared/config.yml
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 443:443
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - $PWD/config/nginx.conf:/etc/nginx/nginx.conf
  panel:
    image: ghcr.io/mhsanaei/3x-ui:v2.2.8
    container_name: panel
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - $PWD/config/x-ui.db:/etc/x-ui/x-ui.db
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
      - XUI_LOG_LEVEL=error
  tor:
    image: lncm/tor:latest
    container_name: tor
    restart: unless-stopped
    volumes:
      - $PWD/config/torrc:/etc/tor/torrc
  warp:
    image: monius/docker-warp-socks
    container_name: warp
    privileged: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    healthcheck:
      test: ["CMD", "curl", "-f", "https://www.cloudflare.com/cdn-cgi/trace"]
      interval: 30s
      timeout: 10s
      retries: 5

