
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - $PWD/html:/usr/share/nginx/html
      - $PWD/config/nginx.conf:/etc/nginx/nginx.conf
  tunnel:
    image: cloudflare/cloudflared
    container_name: tunnel
    restart: unless-stopped
    command: tunnel run
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/config/cloudflared.yml:/etc/cloudflared/config.yml
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  savior:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: savior
    volumes:
      - $PWD/config/x-ui.db:/etc/x-ui/x-ui.db
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
      - XUI_LOG_LEVEL=error
    restart: unless-stopped
