
version: 2.1
workflows:
  version: 2
  commit:
    jobs:
      - rapid_tick
  ticks:
    jobs:
      - rapid_tick
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - main
  tocks:
    jobs:
      - tick
    triggers:
      - schedule:
          cron: "30 * * * *"
          filters:
            branches:
              only:
                - main
jobs:
  tick:
    machine:
      image: default
    steps:
      - checkout
      - run:
          name: Run a tick
          command: timeout --preserve-status 40m docker compose up && docker-compose down || true
          no_output_timeout: 45m
  rapid_tick:
    machine:
      image: default
    steps:
      - checkout
      - run:
          name: Run a rapid tick
          command: timeout --preserve-status 1m docker compose up && docker-compose down || true
          no_output_timeout: 2m
          
