name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rapid_tick:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run rapid tick
        timeout-minutes: 2
        run: timeout --preserve-status 1m docker compose up && docker-compose down || true
        env:
          TUNNEL_TOKEN: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}


