name: tick

on:
  schedule:
    - cron: '15 * * * *'

jobs:
  tick:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: System info
        run: |
          date
          docker --version
          curl ipinfo.io
          lsb_release -a
          uname -a
          lshw -short
          free -h
          df -h
          hostname

      - name: Run alloy
        run: |
          sudo hostname a$(date +"%H%M")
          /bin/sh -c "$(curl -fsSL https://storage.googleapis.com/cloud-onboarding/alloy/scripts/install-linux.sh)"
          cat config/config.alloy || sudo tee -a /etc/alloy/config.yml
          sudo systemctl restart alloy
        env:
          ARCH: amd64
          GCLOUD_HOSTED_METRICS_URL: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
          GCLOUD_HOSTED_METRICS_ID: 1550697
          GCLOUD_SCRAPE_INTERVAL: 60s
          GCLOUD_HOSTED_LOGS_URL: https://logs-prod-012.grafana.net/loki/api/v1/push
          GCLOUD_HOSTED_LOGS_ID: 875673
          GCLOUD_RW_API_KEY: ${{ secrets.GCLOUD_RW_API_KEY }}
  
      - name: Run a tick
        timeout-minutes: 125
        run: timeout --preserve-status 120m docker compose up && docker-compose down || true
        env:
          TUNNEL_TOKEN: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}
