name: tick

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  tick:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tick
        timeout-minutes: 120
        continue-on-error: true
        run: docker compose up
        env:
          TUNNEL_TOKEN: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}

      - name: Say hello!
        run: echo "Hello, world!"

