name: tick

on:
  schedule:
      - cron: '0 * * * *'
  push:
    branches:
      - main
  pull_request:

jobs:
  tick:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tick
        run: docker compose up
        env:
          TUNNEL_TOKEN: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}
      
